##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://small-scream.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /benny-o
# location of code, the full url to your github repository
source-code: https://github.com/small-scream/benny-o

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Benjamin O. Sword
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: The Namesake of Benjamin J. Howard
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "This is a collection of family photos. Benjamin O. Sword was the paternal great-grandfather of Benjamin J. Howard. He was a beloved husband to Evelyn Krebs and father of Shirley Ayne (a.k.a. Teddy)."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: family history; ancestry; American West; old photos; 20th century
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: small-scream

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: benny-o_metadata 
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "Center for Digital Inquiry and Learning (CDIL)"
organization-link: https://cdil.lib.uidaho.edu/
organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
